import {
  Book,
  Briefcase,
  Building2,
  CheckSquare,
  Cloud,
  Code,
  Code2,
  Database,
  Folder,
  Home,
  Info,
  Layout,
  Mail,
  MapPin,
  Menu,
  Network,
  Quote
} from "lucide-react";

import {
  SiAmazonwebservices,
  SiApachekafka,
  SiCss3,
  SiDocker,
  SiExpress,
  SiGithub,
  SiGithubactions,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiLinkedin,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNestjs,
  SiNodedotjs,
  SiPostgresql,
  SiRabbitmq,
  SiReact,
  SiRedis,
  SiSqlite,
  SiTailwindcss,
  SiTypescript
} from "react-icons/si";

export const iconsMaps = {
  navigation: {
    Home,
    About: Info,
    Projects: Folder,
    Experiences: Briefcase,
    Skills: Code,
    Blog: Book,
    Menu,
  },
  social: {
    GitHub: SiGithub,
    LinkedIn: SiLinkedin,
    Mail,
  },
  tech: {
    JavaScript: SiJavascript,
    TypeScript: SiTypescript,
    'Node.js': SiNodedotjs,
    'Nest.js': SiNestjs,
    GraphQL: SiGraphql,
    Express: SiExpress,
    HTML: SiHtml5,
    CSS: SiCss3,
    React: SiReact,
    Tailwind: SiTailwindcss,
    'Material UI': SiMui,
    MySQL: SiMysql,
    PostgreSQL: SiPostgresql,
    MongoDB: SiMongodb,
    Redis: SiRedis,
    SQLite: SiSqlite,
    Docker: SiDocker,
    'CI/CD': SiGithubactions,
    AWS: SiAmazonwebservices,
    Kafka: SiApachekafka,
    RabbitMQ: SiRabbitmq,
  },
  categories: {
    'Back-end Development': Code2,
    'Front-end Development': Layout,
    'Databases': Database,
    'Infrastructure & DevOps': Cloud,
    'Architecture': Network,
    'Methodologies & Quality': CheckSquare,
  },
  misc: {
    Building: Building2,
    Quote,
    MapPin,
  }
};
